apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-rsvp
spec:
  selector:
    matchLabels:
      app: meetup-rsvp
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: meetup-rsvp
    spec:
      containers:
      - image: ysree/meetup-rsvp
        name: meetup-rsvp
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgresdb
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
        - name: WS_URL
          value: ws://stream.meetup.com/2/rsvps
        - name: DB_POOL_MIN_SIZE
          value: 20
        - name: DB_POOL_MAX_SIZE
          value: 20
        - name: LOG_LEVEL
          value: error
        - name: SHOW_ERROR
          value: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
