apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432
  selector:
   app: postgres
